### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by jdyeiter** [foxxyz/multibrowse#15]
Thanks for creating this...much appreciated.

Basically, I have 2 issues:

1) when launching, it never remembers any previous selections we store in cookies.

2) I need all the browser windows we open to be able to share cookies (same site)

Is this possible? I'm assuming there's a way to assign a profile at launch, but I'm not seeing it.

Thanks for your help!

**Comment by foxxyz** [comment]
I'm not sure this is possible.

When multibrowse instantiates the browser windows it [passes a new data directory / profile](https://github.com/foxxyz/multibrowse/blob/master/systems/__init__.py#L35) to every window. Since cookies are stored in that directory, each window is working with a different set that does not persist.

It needs to do this in order to prevent Chrome from:
 1. Opening the next URL in the same window as the previous one
 2. Showing the "restore session?" bubble

However, you're welcome to experiment. If you have an idea to achieve what you want - please share!

Something you could try is to [remove the line that deletes the user data directory on startup](https://github.com/foxxyz/multibrowse/blob/master/systems/__init__.py#L28). That will definitely persist your cookies, but may have other undesirable effects.

**Comment by jdyeiter** [comment]
Thanks for the suggestions. Really appreciate the effort!

I modified the code as you suggested, but it just keeps opening the sites in the same window.

Tried a bunch of options like --new-window, --new-instance, --display:1...nothing helped.

Wound up using displayfusion with a scripted function for multiple websites on different monitors in full screen. The only issue is that you can't open the sites in kiosk mode or it has the same issue of opening on the same monitor.

I'll keep looking, but the displayfusion solution gets me 95% there.

**Comment by foxxyz** [comment]
Ah yeah, that's what I figured would happen. 

It would be nice if some of those CLI args functioned in a more intuitive way... E.G. why doesn't `--new-window` override using the same profile?? 😒

Either way, glad you found something that's closer to what you need.
